### ISSUE TITLE
Install from composer

### ISSUE THREAD

**Issue by bmutinda** [MartinMajor/async-request#1]
Hey @MartinMajor,
Would you mind publishing this project on https://packagist.org so that I can add it as a dependency in my project I try it out?
Thanks.

**Comment by MartinMajor** [comment]
Hi @bmutinda, the project is already on packagist: https://packagist.org/packages/async-request/async-request . I'll add the info to readme, so everyone can find it easily. Thanks!

**Comment by bmutinda** [comment]
@MartinMajor  please do. 
Thanks
