### ISSUE TITLE
php versions < 7 

### ISSUE THREAD

**Issue by bmutinda** [MartinMajor/async-request#2]
Hey @MartinMajor 
I have just noticed that some syntax like `method return type` is only available in PHP7.  How are you going to address for people who are using an older version of php?

**Comment by MartinMajor** [comment]
Yes, I plan to create another branch for PHP5. Thanks!

**Comment by MartinMajor** [comment]
Branch https://github.com/MartinMajor/async-request/tree/v0.1 supports PHP5.4+ .
