### ISSUE TITLE
pause between requests

### ISSUE THREAD

**Issue by dragonattack** [MartinMajor/async-request#3]
Could you please give a hint how can I add pause before making each request?
I don't want all of my requests in queue start simultaneously, but rather one after another, for example every 1 second.
Thank you!

**Comment by MartinMajor** [comment]
Hello, if you don't need multiple requests running in parallel, this library isn't perfect fit for you. But if you still want to use it (for example because of its api), you can set
```php
$asyncRequest->setParallelLimit(1);
```
and use
```php
sleep(1);
```
in your callback.
